pkgbuild revision
kris-nova/aur-falco pull request #1
Opened 2021-09-09 16:08 UTC by FabioLolix

Among others things using sudo and installing in users system instead of the package is prohibited

2021-09-09 16:16 UTC, shibumi approved these changes

2021-09-09 16:18 UTC, shibumi commented
@FabioLolix  this is fine, but it 'changes' the package from being a source package to a precompiled binary package. 
I would suggest we add another folder with your PKGBUILD for the binary package.

What about the following structure:

```
aur-falco:
  README.md
  falco-bin/PKGBUILD
  falco/PKGBUILD 
```

2021-09-09 16:20 UTC, shibumi requested changes

2021-09-09 16:20 UTC, shibumi commented on PKGBUILD
> +source_x86_64=("https://download.falco.org/packages/bin/${arch}/falco-${pkgver}-x86_64.tar.gz")
How do you guarantee that the precompiled binary by falco works with the Arch Linux kernel?

2021-09-09 16:24 UTC, FabioLolix commented
The package actually is already a binary package, I haven't actually changed the source=()

I'm working on a from source pkgbuild too

> What about the following structure:
> 
> ```
> aur-falco:
>   README.md
>   falco-bin/PKGBUILD
>   falco/PKGBUILD 
> ```

don't know if you want to make 2 separate repository or keep one for each that can push to AUR,

2021-09-09 16:29 UTC, shibumi commented
@FabioLolix  why do you think it's a binary package? Kris is explicitly calling `make` here:
```
build() {
    echo "Compiling Kernel Module..."
    cd $pkgname-$pkgver-$arch/usr/src/falco*
    make
```

??

2021-09-09 16:31 UTC, FabioLolix commented
> @FabioLolix why do you think it's a binary package? Kris is explicitly calling `make` here:
> 
> ```
> build() {
>     echo "Compiling Kernel Module..."
>     cd $pkgname-$pkgver-$arch/usr/src/falco*
>     make
> ```

That is for the dkms module

2021-09-09 16:45 UTC, shibumi commented
> That is for the dkms module

a dkms module works completely different in Arch Linux. For a dkms module you have to place a hook into the package and a dkms.conf. See here: https://github.com/archlinux/svntogit-community/blob/f9a512e603615566440b170995439cf626f0836d/trunk/dkms.conf

2021-09-09 16:46 UTC, shibumi requested changes
not convinced yet. I suggest putting the -bin package into a separate directory

2021-09-09 17:03 UTC, FabioLolix commented
> a dkms module works completely different in Arch Linux. For a dkms module you have to place a hook into the package and a dkms.conf.

I'm not familiar with dkms modules but you can see that in my revision the module is not compiled in the pkgbuild, dkms.conf is installed in "${pkgdir}/usr/src/falco-${pkgver}" alongside source and Makefile

Splitting into bin + dkms is a best practice I guess

2021-09-09 22:04 UTC, kris-nova commented
this LGTM - I will merge now and push an update to the official repository shortly

Once my rack is back online we will have automation in place as well 

Thanks for the contribution

2021-09-09 22:04 UTC, merged

2021-09-10 07:20 UTC, shibumi commented
> Splitting into bin + dkms is a best practice I guess 

yep, that's how we do this for the official packages, too :)